import type { SyntheticEvent } from "react";
import { publicUrl } from "./publicUrl";

/**
 * Catalog-grid thumbnails generated by scripts/make_grid_thumbs.py:
 *   /images/products/<id>/01.webp → /images/thumbs/<id>/01-480.webp, 01-720.webp
 * Originals (900×1200) are never modified; they are used as the top srcset
 * candidate and, at full size, in the lightbox / product modal.
 */
const SRC_PREFIX = "/images/products/";
const DST_PREFIX = "/images/thumbs/";
const ORIGINAL_WIDTH = 900;
export const THUMB_WIDTHS = [480, 720] as const;

/** Rendered card width: 2 cols ≤767px, 3 cols ≤1200px, 4 cols (≈290px) above. */
export const GRID_SIZES = "(max-width: 767px) 50vw, (max-width: 1200px) 33vw, 300px";

export function thumbPath(path: string, width: number): string {
  if (!path.startsWith(SRC_PREFIX)) return path;
  const rest = path.slice(SRC_PREFIX.length);
  const dot = rest.lastIndexOf(".");
  const stem = dot < 0 ? rest : rest.slice(0, dot);
  return `${DST_PREFIX}${stem}-${width}.webp`;
}

export function gridImage(path: string): { src: string; srcSet: string; sizes: string } {
  if (!path.startsWith(SRC_PREFIX)) return { src: publicUrl(path), srcSet: "", sizes: GRID_SIZES };
  const srcSet = [
    ...THUMB_WIDTHS.map((w) => `${publicUrl(thumbPath(path, w))} ${w}w`),
    `${publicUrl(path)} ${ORIGINAL_WIDTH}w`,
  ].join(", ");
  return { src: publicUrl(thumbPath(path, THUMB_WIDTHS[0])), srcSet, sizes: GRID_SIZES };
}

/** If a thumbnail is missing, fall back to the original once. */
export function thumbFallback(original: string) {
  return (e: SyntheticEvent<HTMLImageElement>) => {
    const el = e.currentTarget;
    if (el.dataset.fallback) return;
    el.dataset.fallback = "1";
    el.removeAttribute("srcset");
    el.src = publicUrl(original);
  };
}

// Keep references so prefetched images stay in the in-memory image cache.
const warmed = new Map<string, HTMLImageElement>();

/** Fetch a grid thumbnail with the same srcset/sizes the card uses, so the browser picks the same candidate. */
export function warmGridImage(path: string) {
  if (!path || warmed.has(path)) return;
  const { src, srcSet, sizes } = gridImage(path);
  const img = new Image();
  img.decoding = "async";
  if (srcSet) {
    img.sizes = sizes;
    img.srcset = srcSet;
  }
  img.src = src;
  warmed.set(path, img);
}

const fullWarmed = new Set<string>();

/** Warm the full-size original (used by lightbox / modal) on hover or touch. */
export function warmFullImage(path: string | undefined) {
  if (!path || fullWarmed.has(path)) return;
  fullWarmed.add(path);
  const img = new Image();
  img.decoding = "async";
  img.src = publicUrl(path);
}

type IdleWindow = Window & {
  requestIdleCallback?: (cb: (d: { timeRemaining: () => number }) => void, opts?: { timeout: number }) => number;
};

/** Prefetch thumbnails in idle time, a few at a time, after the page has loaded. */
export function prefetchGridImages(paths: string[]) {
  if (typeof window === "undefined") return;
  const conn = (navigator as Navigator & { connection?: { saveData?: boolean } }).connection;
  if (conn?.saveData) return;
  const queue = [...new Set(paths)].filter((p) => !warmed.has(p));
  const w = window as IdleWindow;
  const schedule = (fn: () => void) =>
    w.requestIdleCallback ? w.requestIdleCallback(() => fn(), { timeout: 2000 }) : window.setTimeout(fn, 200);
  const step = () => {
    queue.splice(0, 6).forEach(warmGridImage);
    if (queue.length) schedule(step);
  };
  const start = () => schedule(step);
  if (document.readyState === "complete") start();
  else window.addEventListener("load", start, { once: true });
}
